In [1]:
# Calculate Reward
# Define actions
actions = ["Left", "Right"]

# Give reward for each action
reward = {
    "Left": -1,
    "Right": 10
}

# Print rewards
for action in actions:
    print("Action:", action)
    print("Reward:", reward[action])

Action: Left
Reward: -1
Action: Right
Reward: 10


In [2]:
# Calculate Discounted Reward
# Rewards received
rewards = [10, 5, 2]

# Discount factor
gamma = 0.9

discounted_reward = 0

for i in range(len(rewards)):
    discounted_reward += (gamma ** i) * rewards[i]

print("Rewards:", rewards)
print("Discounted Reward:", discounted_reward)

Rewards: [10, 5, 2]
Discounted Reward: 16.12


In [3]:
# Calculate Optimal Q Values
import numpy as np

# Q Table
Q = np.array([
    [0, 5],
    [2, 8],
    [4, 7]
])

print("Q Table")
print(Q)

print("\nOptimal Q Value for each State")

for i in range(len(Q)):
    print("State", i, "=", np.max(Q[i]))

Q Table
[[0 5]
 [2 8]
 [4 7]]

Optimal Q Value for each State
State 0 = 5
State 1 = 8
State 2 = 7


In [4]:
#Implement Q-Learning (Without Gym)
import numpy as np
# Q Table
Q = np.array([
    [0, 5],
    [2, 8],
    [4, 7]
])

print("Q Table")
print(Q)

print("\nOptimal Q Value for each State")

for i in range(len(Q)):
    print("State", i, "=", np.max(Q[i]))

Q Table
[[0 5]
 [2 8]
 [4 7]]

Optimal Q Value for each State
State 0 = 5
State 1 = 8
State 2 = 7


In [5]:
#Selecting Optimal Action
import numpy as np

Q = np.array([
    [10, 25],
    [40, 30],
    [18, 45]
])

print("Q Table")

print(Q)

print("\nBest Action")

for state in range(len(Q)):

    best_action = np.argmax(Q[state])

    print("State", state,
          "Best Action =", best_action)

Q Table
[[10 25]
 [40 30]
 [18 45]]

Best Action
State 0 Best Action = 1
State 1 Best Action = 0
State 2 Best Action = 1
